import 'package:flutter/material.dart';

class ListDropDown {
  final int id;
  final String label;
  

  ListDropDown(this.id, this.label,);
  
}


List<ListDropDown> jobtitle = [
 
ListDropDown(1, 'Accountant'),
ListDropDown(2, 'Android Developer'),
ListDropDown(3, 'Architect'),
ListDropDown(4, 'Assistant Manager'),
ListDropDown(5, 'Back Office Executive'),
ListDropDown(6, 'Business Development Manager'),
ListDropDown(7, 'Chef'),
ListDropDown(8, 'Civil Engineer'),
ListDropDown(9, 'Content Writer'),
ListDropDown(10, 'Customer Service Executive'),
ListDropDown(11, 'Data Analyst'),
ListDropDown(12, 'Delivery Boy'),
ListDropDown(13, 'Dentist'),
ListDropDown(14, 'Digital Marketing Executive'),
ListDropDown(15, 'Doctor'),
ListDropDown(16, 'Electrical Engineer'),
ListDropDown(17, 'Event Manager'),
ListDropDown(18, 'Fashion Designer'),
ListDropDown(19, 'Finance Manager'),
ListDropDown(20, 'Graphic Designer'),
ListDropDown(21, 'HR Manager'),
ListDropDown(22, 'Java Developer'),
ListDropDown(23, 'Lawyer'),
ListDropDown(24, 'Marketing Manager'),
ListDropDown(25, 'Mechanical Engineer'),
ListDropDown(26, 'Nurse'),
ListDropDown(27, 'Operations Manager'),
ListDropDown(28, 'Pharmacist'),
ListDropDown(29, 'Product Manager'),
ListDropDown(30, 'Project Manager'),
ListDropDown(31, 'Quality Assurance Engineer'),
ListDropDown(32, 'Receptionist'),
ListDropDown(33, 'Sales Executive'),
ListDropDown(34, 'Software Developer'),
ListDropDown(35, 'Software Engineer'),
ListDropDown(36, 'Store Manager'),
ListDropDown(37, 'Supply Chain Manager'),
ListDropDown(38, 'Teacher'),
ListDropDown(39, 'Technical Support Engineer'),
ListDropDown(40, 'UI/UX Designer'),
ListDropDown(41, 'Warehouse Manager'),
ListDropDown(42, 'Web Developer'),
ListDropDown(43, 'Account Manager'),
ListDropDown(44, 'Administrative Assistant'),
ListDropDown(45, 'Branch Manager'),
ListDropDown(46, 'Business Analyst'),
ListDropDown(47, 'Call Center Executive'),
ListDropDown(48, 'Customer Relationship Manager'),
ListDropDown(49, 'Cyber Security Specialist'),
ListDropDown(50, 'Database Administrator'),
ListDropDown(51, 'Digital Marketing Manager'),
ListDropDown(52, 'Electrical Technician'),
ListDropDown(53, 'Executive Assistant'),
ListDropDown(54, 'Finance Analyst'),
ListDropDown(55, 'Front End Developer'),
ListDropDown(56, 'Full Stack Developer'),
ListDropDown(57, 'Human Resources Executive'),
ListDropDown(58, 'IT Support Specialist'),
ListDropDown(59, 'Logistics Manager'),
ListDropDown(60, 'Maintenance Technician'),
ListDropDown(61, 'Network Administrator'),
ListDropDown(62, 'Office Assistant'),
ListDropDown(63, 'Operations Executive'),
ListDropDown(64, 'Procurement Manager'),
ListDropDown(65, 'Product Designer'),
ListDropDown(66, 'Recruiter'),
ListDropDown(67, 'Research Analyst'),
ListDropDown(68, 'Risk Manager'),
ListDropDown(69, 'Sales Manager'),
ListDropDown(70, 'Security Guard'),
ListDropDown(71, 'SEO Specialist'),
ListDropDown(72, 'Social Media Manager'),
ListDropDown(73, 'Software Tester'),
ListDropDown(74, 'Solution Architect'),
ListDropDown(75, 'Systems Engineer'),
ListDropDown(76, 'Talent Acquisition Specialist'),
ListDropDown(77, 'Technical Writer'),
ListDropDown(78, 'Training Coordinator'),
ListDropDown(79, 'Video Editor'),
ListDropDown(80, 'Virtual Assistant'),
ListDropDown(81, 'Warehouse Supervisor'),
ListDropDown(82, 'Administrative Manager'),
ListDropDown(83, 'Audit Manager'),
ListDropDown(84, 'Business Operations Manager'),
ListDropDown(85, 'Channel Sales Manager'),
ListDropDown(86, 'Client Service Executive'),
ListDropDown(87, 'Cloud Engineer'),
ListDropDown(88, 'Commercial Manager'),
ListDropDown(89, 'Corporate Lawyer'),
ListDropDown(90, 'Data Scientist'),
ListDropDown(91, 'Delivery Manager'),
ListDropDown(92, 'Design Engineer'),
ListDropDown(93, 'Environmental Engineer'),
ListDropDown(94, 'Facility Manager'),
ListDropDown(95, 'HR Business Partner'),
ListDropDown(96, 'Information Security Analyst'),
ListDropDown(97, 'Internal Auditor'),
ListDropDown(98, 'Mechanical Technician'),
ListDropDown(99, 'Mobile Developer'),
ListDropDown(100, 'Operations Coordinator')
];
List<ListDropDown>menuItems1 =[
  ListDropDown(1, 'Home', ),
  ListDropDown(2, 'Profile',),
  ListDropDown(3, 'Settings', ),
  ListDropDown(4, 'Favorites', ),
  ListDropDown(5, 'Notifications', )
];